version: "3"
services:     
  mysql:
    image: mysql:8.0.26
    ports:
      - "3406:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 0987_Poiu_Root
      MYSQL_DATABASE: airflow
      MYSQL_USER: newuser
      MYSQL_PASSWORD: 0987_Poiu
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    command:  mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  airflow:
    image: my-airflow
    entrypoint: ./scripts/entrypoint.sh
    depends_on:
        - mysql
    env_file:
        - .env
    volumes:
        - ./dags:/opt/airflow/dags
        - ./logs:/opt/airflow/logs
        - ./scripts:/opt/airflow/scripts
    ports:
        - "8080:8080"
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30